language: node_js
node_js:
- '6'
script:
- npm test
- curl -O https://raw.githubusercontent.com/danvk/travis-weigh-in/master/weigh_in.py
  && python weigh_in.py index-built.js
deploy:
  provider: npm
  email: ui-admin.e@klarna.com
  api_key:
    secure: JveRJbGP5jYktjXJ17yfNp+iR0R1AEMJOBSzbK3qg4iMnlETYWbd590yq2RMjNFBrBJGSkxbXoZpzeFfD5H547CELEJ8tyJJ0V8XSAXqB3SijytEf+t0V0VyBPYUMMuJ8YMmrikZfLVd8YXPy1hZrr1gN20QSetQJ3n8Z54JswkbyDvOiHkR5YnWgOtYu+8+s5fJ10XCP2u7gHw/7sKuDL1HxKW8vnWA5et076YoACM0mEepgo6wxkbMB1B99bYYqDzzZmFEYWaqTZjUC1bkMGfTA2Uv8eyZPiItHWnv4zoa9atoL1C4sYiir/VSrPNnurBdlyMTJu7mgECahnm5ORXzZ1nGLfGD64jzixWAGC3mCy6ukgQzlOWpWDSfePb7Ni8Vg/5bpDk4gNlVrxKpyfZn3GS+P1nfZ5Vi0xRceVBNQ2oDSAXPRldR9IS2dHErPl20D2t2+JLe4GkRzx/jQYO/EIqU396FDUDyHCiRlFj5GlDmy8nOw83H12syUZWQQKWoA5YgUoaCSK+dL5SjFEj/Cabh7+DuV0tEeU7lNUUT7NlvBSLBhdas29RDJ9Xc81h71hfumAPQUl5MIJhqclE+bV9TJB+aJRs207qGbzSjvoQ5+xKoU64iOSmfZd2x9Peqb3ibtTNFxkXIGvrufRuL41np810Pfd5PqjEfYvo=
  on:
    tags: true
    repo: klarna/ui
