addons:
  sauce_connect:
    username: "klarnareact"
    access_key:
      secure: "Gxryl2yic9gx6hidFNd0Yi40m5eCe+Htb6ZMWWHnFhcFk8Yz2oEVEXNy9Kr94AxaooXO1LFgHhQteJ4AzgwMwPxJknel3ky52ogk7Ly3fCND/YQErgSvRjopY+6XCAw5gxUNUj2str6QIM3r9zZufJyl1Zs1vjQ6OszbyRmg3R41XufVeeszN8kENta3SOxtvPp88QBECh1A8kMjT35/e4Et6lRTw0mKHWVLK2T18PkGHMhS9nqe2/lIR+emqWThn4TJOXGwZ64DnyWDXI1Ej31E4VfqYwukcLBCzIpt6XTfHH6evH1m8Pp0MYvj6hp3Be898a1NGPxib4HGUNuzMQTZP4XYmWQL/mVnEcTrGq/9zd0D8IzirqGVw+QzTdjDZryZebYAEUZfaW5ybES98PKN6uM3Q9+TVyu5Tqqaf7irfIJQZKHTEObyaFgiF5ieA5CtuHhOXWpvCRh1AEzlDgujOAWFBIvLTxzoquVqvxfU3tlZXrDEHhUnCZbGLPr1uhMmAZFySxFqHyOG8DdXEjRb2zawUMC1V8KM9s5CLwFJjxBktobrijl8/XFhYgeTvfBQMDGHNorKQAw4lIfOQsSOSLVG0NGTGSAUPhtK+G6RsJd18H3mfqyM6mvxoLvjfEZEDuVvqhJXZu8fFqwD9L7DwMuQnekX22HPCI6YklQ="
language: node_js
node_js:
  - "4"
  - "5"
before_script:
  - npm install
script:
  - npm run lint
  - BROWSER=sl_ios_safari,PhantomJS npm test
